warns = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::cargo",
]

allow = [
    "clippy::module_name_repetitions",
]

deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
]

msrv = "1.76.0"
